global using System.ComponentModel;
global using Microsoft.Win32.SafeHandles;
global using Serilog;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Diagnostics.CodeAnalysis;
global using System.Net;
global using System.Net.Sockets;
global using System.Reflection;